services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    ConnectHolland\UserBundle\EventSubscriber\CreateOAuthUserSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    ConnectHolland\UserBundle\Security\OAuthUserProvider:
        arguments:
            $doctrine: '@Doctrine\Persistence\ManagerRegistry'
            $eventDispatcher: '@event_dispatcher'

    ConnectHolland\UserBundle\Routing\OAuthRouteLoader:
        lazy: true
        public: true
        arguments:
            $resourceOwnerMaps: []
        tags:
            - { name: 'routing.loader' }

    connectholland_user.routing_oauth_route_loader: '@ConnectHolland\UserBundle\Routing\OAuthRouteLoader'
